const fs = require("fs");
const path = require("path");
const { spawn, execSync } = require("child_process");
const { LOCAL_VERSION } = require("./config");
const { extractFormId } = require("./url");
const { logIssue } = require("./issues");
const { runPlaywrightCli } = require("./playwright");
const { parseSnapshotRefs, refToLocator } = require("./snapshot");

function convertCommandToPlaywright(args, refMap) {
  const cmd = args[0];

  switch (cmd) {
    case "open":
    case "goto":
      return `await page.goto('${args[1]}');`;

    case "fill": {
      const locator = refToLocator(args[1], refMap);
      const value = args.slice(2).join(" ");
      return `await ${locator}.fill('${value.replace(/'/g, "\\'")}');`;
    }

    case "click": {
      const locator = refToLocator(args[1], refMap);
      return `await ${locator}.click();`;
    }

    case "dblclick": {
      const locator = refToLocator(args[1], refMap);
      return `await ${locator}.dblclick();`;
    }

    case "select": {
      const locator = refToLocator(args[1], refMap);
      const option = args.slice(2).join(" ");
      return `await ${locator}.selectOption({ label: '${option.replace(/'/g, "\\'")}' });`;
    }

    case "check": {
      const locator = refToLocator(args[1], refMap);
      return `await ${locator}.check();`;
    }

    case "uncheck": {
      const locator = refToLocator(args[1], refMap);
      return `await ${locator}.uncheck();`;
    }

    case "hover": {
      const locator = refToLocator(args[1], refMap);
      return `await ${locator}.hover();`;
    }

    case "press":
      return `await page.keyboard.press('${args[1]}');`;

    case "type":
      return `await page.keyboard.type('${args.slice(1).join(" ")}');`;

    case "screenshot": {
      const filenameIdx = args.indexOf("--filename");
      const filename =
        filenameIdx >= 0 ? args[filenameIdx + 1] : "screenshot.png";
      const fullPage = args.includes("--full-page");
      return `await page.screenshot({ path: '${filename.replace(/\\/g, "/")}', fullPage: ${fullPage} });`;
    }

    case "snapshot":
      return null; // observation only — skip

    case "close":
      return null; // handled by test cleanup

    case "eval":
    case "run-code":
      return `// eval: ${args.slice(1).join(" ").substring(0, 120)}`;

    case "go-back":
      return "await page.goBack();";

    case "go-forward":
      return "await page.goForward();";

    case "reload":
      return "await page.reload();";

    case "resize":
      return `await page.setViewportSize({ width: ${args[1]}, height: ${args[2]} });`;

    default:
      return `// TODO: ${args.join(" ")}`;
  }
}

function generateTestScript(recording, outputDir, config) {
  const commands = recording.commands || [];
  const formUrl = config.lastTestUrl || "";
  const formId = formUrl ? extractFormId(formUrl) : "form";

  let currentRefMap = {};
  const lines = [];

  for (const cmd of commands) {
    const cmdArgs = cmd.args;

    if (cmdArgs[0] === "snapshot") {
      const filenameIdx = cmdArgs.indexOf("--filename");
      if (filenameIdx >= 0) {
        const snapshotPath = cmdArgs[filenameIdx + 1];
        if (fs.existsSync(snapshotPath)) {
          const newRefs = parseSnapshotRefs(
            fs.readFileSync(snapshotPath, "utf8"),
          );
          currentRefMap = { ...currentRefMap, ...newRefs };
        }
      }
      continue;
    }

    const line = convertCommandToPlaywright(cmdArgs, currentRefMap);
    if (line !== null) {
      lines.push(line);
    }
  }

  const timestamp = new Date().toISOString();
  const tracePath = path.join(outputDir, "trace.zip").replace(/\\/g, "/");
  const errorScreenshot = path.join(outputDir, "error.png").replace(/\\/g, "/");

  return `// Generated by form-tester v${LOCAL_VERSION}
// Source: ${path.join(outputDir, "recording.json").replace(/\\/g, "/")}
// Date: ${timestamp}
// Form: ${formId}
//
// Usage:
//   form-tester run ${path.join(outputDir, "test.generated.js").replace(/\\/g, "/")} --trace
//   node ${path.join(outputDir, "test.generated.js").replace(/\\/g, "/")} --trace

let pw;
try { pw = require('playwright'); } catch {
  try { pw = require('playwright-core'); } catch {
    console.error('\\n  Playwright not installed. Run:\\n    npm install -g playwright\\n    npx playwright install chromium\\n');
    process.exit(1);
  }
}

const TRACE = process.argv.includes('--trace');
const HEADLESS = process.argv.includes('--headless');

(async () => {
  const browser = await pw.chromium.launch({ headless: HEADLESS });
  const context = await browser.newContext();

  if (TRACE) {
    await context.tracing.start({ screenshots: true, snapshots: true, sources: true });
  }

  const page = await context.newPage();

  try {
${lines.map((l) => "    " + l).join("\n")}

    console.log('Test completed successfully');
  } catch (error) {
    console.error('Test failed:', error.message);
    await page.screenshot({ path: '${errorScreenshot}', fullPage: true }).catch(() => {});
    process.exitCode = 1;
  } finally {
    if (TRACE) {
      await context.tracing.stop({ path: '${tracePath}' });
      console.log('Trace saved: ${tracePath}');
      console.log('View:  npx playwright show-trace ${tracePath}');
    }
    await browser.close();
  }
})();
`;
}

async function handleGenerate(config, flags) {
  const outputDir = flags.outputDir || config.lastRunDir;
  const recordingPath =
    flags.recordingPath ||
    (outputDir ? path.join(outputDir, "recording.json") : null);

  if (!recordingPath || !fs.existsSync(recordingPath)) {
    console.error(
      "Recording not found. Run a test first, or specify: form-tester generate <recording.json>",
    );
    return 1;
  }

  const recording = JSON.parse(fs.readFileSync(recordingPath, "utf8"));
  console.log(`Generating test from ${recording.commandCount} commands...`);

  const testCode = generateTestScript(
    recording,
    path.dirname(recordingPath),
    config,
  );
  const testPath = path.join(path.dirname(recordingPath), "test.generated.js");
  fs.writeFileSync(testPath, testCode);

  console.log(`Generated: ${testPath}`);
  console.log(`\nRun with:  form-tester run ${testPath} --trace`);
  console.log(`Or:        node ${testPath} --trace`);

  return testPath;
}

function findPlaywrightNodeModules() {
  try {
    const resolved = require.resolve("playwright");
    const parts = resolved.replace(/\\/g, "/").split("/");
    const nmIdx = parts.lastIndexOf("node_modules");
    if (nmIdx >= 0) return parts.slice(0, nmIdx + 1).join(path.sep);
  } catch {
    /* not found locally */
  }

  try {
    const globalDir = execSync("npm root -g", {
      encoding: "utf8",
      stdio: ["pipe", "pipe", "pipe"],
    }).trim();
    if (fs.existsSync(path.join(globalDir, "playwright"))) return globalDir;
    if (fs.existsSync(path.join(globalDir, "playwright-core")))
      return globalDir;
  } catch {
    /* npm not available */
  }

  return null;
}

async function handleRun(testFile, config, flags) {
  if (!fs.existsSync(testFile)) {
    console.error(`Test file not found: ${testFile}`);
    return 1;
  }

  const scriptArgs = [];
  if (flags.trace) scriptArgs.push("--trace");
  if (flags.headless) scriptArgs.push("--headless");

  const env = { ...process.env };
  const pwModules = findPlaywrightNodeModules();
  if (pwModules) {
    env.NODE_PATH =
      pwModules + (env.NODE_PATH ? path.delimiter + env.NODE_PATH : "");
  }

  const cmdDisplay =
    `node ${path.basename(testFile)} ${scriptArgs.join(" ")}`.trim();
  console.log(`Running: ${cmdDisplay}`);
  const startTime = Date.now();

  const code = await new Promise((resolve) => {
    const child = spawn(process.execPath, [testFile, ...scriptArgs], {
      stdio: "inherit",
      env,
    });
    child.on("error", (err) => {
      console.error(`Failed to launch: ${err.message}`);
      resolve(1);
    });
    child.on("exit", (c) => resolve(c ?? 0));
  });

  const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
  console.log(`\n${code === 0 ? "PASS" : "FAIL"} (${elapsed}s)`);

  if (flags.trace) {
    const tracePath = path.join(path.dirname(testFile), "trace.zip");
    if (fs.existsSync(tracePath)) {
      console.log(`Trace: ${tracePath}`);
      console.log(`View:  npx playwright show-trace ${tracePath}`);
    }
  }

  return code;
}

async function handleReplay(filePath) {
  if (!fs.existsSync(filePath)) {
    console.error(`Recording not found: ${filePath}`);
    process.exit(1);
  }
  const recording = JSON.parse(fs.readFileSync(filePath, "utf8"));
  console.log(
    `Replaying ${recording.commandCount} commands from ${recording.startedAt}`,
  );
  console.log("");

  for (let i = 0; i < recording.commands.length; i++) {
    const cmd = recording.commands[i];
    console.log(
      `[${i + 1}/${recording.commandCount}] playwright-cli ${cmd.args.join(" ")}`,
    );
    const code = await runPlaywrightCli(cmd.args);
    if (code !== 0) {
      logIssue(
        "other",
        `Replay command failed: playwright-cli ${cmd.args.join(" ")} (exit ${code})`,
      );
      console.error(`Command failed with exit code ${code}. Stopping replay.`);
      process.exit(1);
    }
  }

  console.log("\nReplay complete.");
}

module.exports = {
  convertCommandToPlaywright,
  generateTestScript,
  handleGenerate,
  handleRun,
  handleReplay,
  findPlaywrightNodeModules,
};
